export enum PageTitle {
  NOT_FOUND = 'Not Found',
  UNEXPECTED_ERROR = 'Unexpected Error',
  REGISTRATION = 'Register',
  REGISTRATION_EMAIL_SENT = 'Check Your Inbox',
  RESET = 'Reset Password',
  MAGIC_LINK = 'Sign in',
  EMAIL_SENT = 'Check Your Inbox',
  RESET_RESEND = 'Resend Reset Password',
  SIGN_IN = 'Sign in',
  SET_PASSWORD = 'Create Password',
  SET_PASSWORD_COMPLETE = 'Password Set',
  SET_PASSWORD_RESEND = 'Resend Set Password',
  CHANGE_PASSWORD = 'Change Password',
  CHANGE_PASSWORD_COMPLETE = 'Password Changed',
  VERIFY_EMAIL = 'Verify Email',
  WELCOME = 'Welcome',
  WELCOME_RESEND = 'Resend Welcome Email',
}
