import * as crypto from 'crypto';
import { injectAndCheckAxe } from '../../../support/cypress-axe';

describe('Registration email sent page', () => {
  const existingWithoutPassword = {
    serverId: Cypress.env('MAILOSAUR_SERVER_ID'),
    serverDomain: Cypress.env('MAILOSAUR_SERVER_ID') + '.mailosaur.net',
    email:
      'registrationEmailSentPage@' +
      Cypress.env('MAILOSAUR_SERVER_ID') +
      '.mailosaur.net',
  };

  const existingWithPassword = {
    serverId: Cypress.env('MAILOSAUR_SERVER_ID'),
    serverDomain: Cypress.env('MAILOSAUR_SERVER_ID') + '.mailosaur.net',
    email: 'signIn@' + Cypress.env('MAILOSAUR_SERVER_ID') + '.mailosaur.net',
  };

  const unregisteredAccount = {
    serverId: Cypress.env('MAILOSAUR_SERVER_ID'),
    serverDomain: Cypress.env('MAILOSAUR_SERVER_ID') + '.mailosaur.net',
    email:
      'registrationTest+' +
      crypto.randomUUID() +
      '@' +
      Cypress.env('MAILOSAUR_SERVER_ID') +
      '.mailosaur.net',
  };

  // PLAY_SESSION_2 encrypted email is generated by identity-frontend when you start a guest registration.
  // If the test email changes, copy this cookie from the browser to the encryptedEmail variable.
  const encryptedEmail =
    'eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImVtYWlsIjoicmVnaXN0cmF0aW9uRW1haWxTZW50UGFnZUB5dGNwMG44cS5tYWlsb3NhdXIubmV0In0sImV4cCI6MTYzMTU0NjA1NCwibmJmIjoxNjMxNTQ0MjU0LCJpYXQiOjE2MzE1NDQyNTR9.2QqQA0adO31fNeiOQGih7DdgxPaJeWJhwFWBAzanDRQ';

  context('A11y checks', () => {
    it('has no detectable a11y violations on the registration email sent page', () => {
      cy.setCookie('PLAY_SESSION_2', encryptedEmail, {
        log: true,
      });
      cy.visit(`/register/email-sent`);
      injectAndCheckAxe();
    });
  });

  it('should load the page with a success banner given a valid encrypted email cookie', () => {
    cy.setCookie('PLAY_SESSION_2', encryptedEmail, {
      log: true,
    });
    cy.visit(`/register/email-sent`);
    cy.contains('Email sent');
    cy.contains(existingWithoutPassword.email);
    cy.contains('Resend email');
    cy.contains('Change email address');
  });

  // Depends on a Guest account already created using this email.
  it('should resend the email when the resend button is clicked', () => {
    cy.setCookie('PLAY_SESSION_2', encryptedEmail, {
      log: true,
    });
    cy.visit(`/register/email-sent`);
    cy.contains(existingWithoutPassword.email);
    const timeRequestWasMade = new Date();
    cy.contains('Resend email').click();
    cy.mailosaurGetMessage(
      existingWithoutPassword.serverId,
      {
        sentTo: existingWithoutPassword.email,
      },
      {
        receivedAfter: timeRequestWasMade,
      },
    ).then((email) => {
      const id = email.id ?? '';
      const body = email.html?.body ?? '';
      expect(body).to.have.string('Complete registration');
      // Extract the welcome token, so we can redirect to the welcome flow.
      const match = body.match(/theguardian.com\/welcome\/([^"]*)/) ?? '';
      const token = match[1];
      cy.visit(`/welcome/${token}`);
      cy.contains('Create password');
      cy.mailosaurDeleteMessage(id);
    });
  });

  it('should resend "Complete Registration" email when a new user registers which is same as initial email sent', () => {
    cy.visit('/register');
    cy.get('input[name=email]').type(unregisteredAccount.email);
    const timeRequestWasMadeInitialEmail = new Date();
    cy.get('[data-cy="register-button"]').click();

    cy.contains('Email sent');
    cy.contains(unregisteredAccount.email);
    cy.contains('Resend email');
    cy.contains('Change email address');

    // test and delete initial email
    cy.mailosaurGetMessage(
      unregisteredAccount.serverId,
      {
        sentTo: unregisteredAccount.email,
      },
      {
        receivedAfter: timeRequestWasMadeInitialEmail,
      },
    ).then((email) => {
      const id = email.id ?? '';
      const body = email.html?.body;
      expect(body).to.have.string('Complete registration');
      cy.mailosaurDeleteMessage(id);
    });

    const timeRequestWasMade = new Date();
    cy.contains('Resend email').click();
    cy.contains('Email sent');
    cy.contains(unregisteredAccount.email);
    // test and delete resent email
    cy.mailosaurGetMessage(
      unregisteredAccount.serverId,
      {
        sentTo: unregisteredAccount.email,
      },
      {
        receivedAfter: timeRequestWasMade,
      },
    ).then((email) => {
      const id = email.id ?? '';
      const body = email.html?.body;
      expect(body).to.have.string('Complete registration');
      cy.mailosaurDeleteMessage(id);
    });
  });

  it('should resend account exists without password email when an existing user without password registers which is same as initial email sent', () => {
    cy.visit('/register');
    cy.get('input[name=email]').type(existingWithoutPassword.email);
    const timeRequestWasMadeInitialEmail = new Date();
    cy.get('[data-cy="register-button"]').click();

    cy.contains('Email sent');
    cy.contains(existingWithoutPassword.email);
    cy.contains('Resend email');
    cy.contains('Change email address');

    // test and delete initial email
    cy.mailosaurGetMessage(
      existingWithoutPassword.serverId,
      {
        sentTo: existingWithoutPassword.email,
      },
      {
        receivedAfter: timeRequestWasMadeInitialEmail,
      },
    ).then((email) => {
      const id = email.id ?? '';
      const body = email.html?.body;
      expect(body).to.have.string('This account already exists');
      expect(body).to.have.string(
        'To continue to your account please click below to create a password.',
      );
      expect(body).to.have.string('This link is only valid for 30 minutes.');
      expect(body).to.have.string('Create password');
      cy.mailosaurDeleteMessage(id);
    });

    const timeRequestWasMade = new Date();
    cy.contains('Resend email').click();
    cy.contains('Email sent');
    cy.contains(existingWithoutPassword.email);
    // test and delete resent email
    cy.mailosaurGetMessage(
      existingWithoutPassword.serverId,
      {
        sentTo: existingWithoutPassword.email,
      },
      {
        receivedAfter: timeRequestWasMade,
      },
    ).then((email) => {
      const id = email.id ?? '';
      const body = email.html?.body;
      expect(body).to.have.string('This account already exists');
      expect(body).to.have.string(
        'To continue to your account please click below to create a password.',
      );
      expect(body).to.have.string('This link is only valid for 30 minutes.');
      expect(body).to.have.string('Create password');
      cy.mailosaurDeleteMessage(id);
    });
  });

  it('should resend "Account Exists" email when an existing user with password registers which is same as initial email sent', () => {
    cy.visit('/register');
    cy.get('input[name=email]').type(existingWithPassword.email);
    const timeRequestWasMadeInitialEmail = new Date();
    cy.get('[data-cy="register-button"]').click();

    cy.contains('Email sent');
    cy.contains(existingWithPassword.email);
    cy.contains('Resend email');
    cy.contains('Change email address');

    // test and delete initial email
    cy.mailosaurGetMessage(
      existingWithPassword.serverId,
      {
        sentTo: existingWithPassword.email,
      },
      {
        receivedAfter: timeRequestWasMadeInitialEmail,
      },
    ).then((email) => {
      const id = email.id ?? '';
      const body = email.html?.body ?? '';
      expect(body).to.have.string(
        'You are already registered with the Guardian.',
      );
      cy.mailosaurDeleteMessage(id);
    });

    const timeRequestWasMade = new Date();
    cy.contains('Resend email').click();
    cy.contains('Email sent');
    cy.contains(existingWithPassword.email);
    // test and delete resent email
    cy.mailosaurGetMessage(
      existingWithPassword.serverId,
      {
        sentTo: existingWithPassword.email,
      },
      {
        receivedAfter: timeRequestWasMade,
      },
    ).then((email) => {
      const id = email.id ?? '';
      const body = email?.html?.body ?? '';
      expect(body).to.have.string(
        'You are already registered with the Guardian.',
      );
      cy.mailosaurDeleteMessage(id);
    });
  });

  it('should navigate back to the correct page when change email is clicked', () => {
    cy.setCookie('PLAY_SESSION_2', encryptedEmail, {
      log: true,
    });
    cy.visit(`/register/email-sent`);
    cy.contains('Change email address').click();
    cy.contains('Sign in');
    cy.title().should('eq', 'Sign in | The Guardian');
  });

  it('should render properly if the encrypted email cookie is not set', () => {
    cy.visit(`/register/email-sent`);
    cy.contains('Change email address');
    cy.contains('Email sent');
  });
});
