import { Newsletters, NewslettersWithImages } from '@/shared/model/Newsletter';
import {
	AFTERNOON_UPDATE_AU_SQUARE_IMAGE,
	HEADLINES_US_SQUARE_IMAGE,
	MORNING_MAIL_AU_SQUARE_IMAGE,
	SAVED_FOR_LATER_AU_SQUARE_IMAGE,
	THE_CRUNCH_AU_SQUARE_IMAGE,
	THE_STAKES_US_SQUARE_IMAGE,
	TRUMP_ON_TRIAL_US_SQUARE_IMAGE,
	WELL_ACTUALLY_SQUARE_IMAGE,
} from '@/client/assets/newsletters';

export const NEWSLETTER_IMAGES: Record<NewslettersWithImages, string> = {
	[Newsletters.MORNING_MAIL_AU]: MORNING_MAIL_AU_SQUARE_IMAGE,
	[Newsletters.AFTERNOON_UPDATE_AU]: AFTERNOON_UPDATE_AU_SQUARE_IMAGE,
	[Newsletters.SAVED_FOR_LATER_AU]: SAVED_FOR_LATER_AU_SQUARE_IMAGE,
	[Newsletters.THE_CRUNCH_AU]: THE_CRUNCH_AU_SQUARE_IMAGE,
	[Newsletters.HEADLINES_US]: HEADLINES_US_SQUARE_IMAGE,
	[Newsletters.THE_STAKES_US]: THE_STAKES_US_SQUARE_IMAGE,
	[Newsletters.WELL_ACTUALLY]: WELL_ACTUALLY_SQUARE_IMAGE,
	[Newsletters.TRUMP_ON_TRIAL_US]: TRUMP_ON_TRIAL_US_SQUARE_IMAGE,
};
