name: playwright-mocked
on:
  workflow_call:
jobs:
  playwright-mocked:
    name: Playwright mocked tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5, 6]
        shardTotal: [6]
    timeout-minutes: 15
    permissions:
      contents: read
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps Redis port 6379 on service container to the host
          - 6379:6379
    env:
      PORT: 8861
      ENVIRONMENT: production
      STAGE: DEV
      BASE_URI: profile.thegulocal.com
      IDAPI_CLIENT_ACCESS_TOKEN: fakekey
      IDAPI_BASE_URL: http://localhost:9000
      DEFAULT_RETURN_URI: https://m.code.dev-theguardian.com
      SIGN_IN_PAGE_URL: https://profile.thegulocal.com/signin
      OAUTH_BASE_URL: https://oauth.code.dev-theguardian.com
      MEMBERS_DATA_API_URL: http://localhost:9000
      USER_BENEFITS_API_URL: http://localhost:9000
      PRINT_PROMO_SNS_TOPIC_ARN: fakearn
      IS_HTTPS: true
      APP_SECRET: devsecret
      CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.CYPRESS_MAILOSAUR_API_KEY }}
      CYPRESS_MAILOSAUR_SERVER_ID: ${{ secrets.CYPRESS_MAILOSAUR_SERVER_ID }}
      CYPRESS_OKTA_ANDROID_CLIENT_ID: androidclientid
      # These are public test keys provided by Google for testing.
      # https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do
      GOOGLE_RECAPTCHA_SITE_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      GOOGLE_RECAPTCHA_SECRET_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      ENCRYPTION_SECRET_KEY: f3d87b231ddd6f50d99e227c5bc9b7cbb649387b321008df412fd73805ac2e32
      OKTA_ORG_URL: http://localhost:9000
      OKTA_API_TOKEN: oktatoken
      OKTA_CUSTOM_OAUTH_SERVER: oktaoauthserverid
      OKTA_CLIENT_ID: oktaclientid
      OKTA_CLIENT_SECRET: oktaclientsecret
      OKTA_IDP_APPLE: oktaappleidp
      OKTA_IDP_GOOGLE: oktagoogleidp
      OKTA_GUARDIAN_USERS_ALL_GROUP_ID: oktaGuardianUserGroupId
      REDIS_HOST: localhost
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_SSL_ON: false
      RATE_LIMITER_CONFIG: '{"enabled":true,"defaultBuckets":{"globalBucket":{"capacity":500,"addTokenMs":50}}}'
      DELETE_ACCOUNT_STEP_FUNCTION_URL: delete-account-step-function-url
      DELETE_ACCOUNT_STEP_FUNCTION_API_KEY: delete-account-step-function-api-key
      # Required for the tests to run as we're unable to verify the created certs
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      # Used to tell Gateway server we're running in Playwright
      RUNNING_IN_PLAYWRIGHT: true
      RUNNING_IN_PLAYWRIGHT_MOCKED: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup OS, Nginx, and Certs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libnss3-tools
          sudo service nginx restart
          wget -q https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
          wget -q https://github.com/guardian/dev-nginx/releases/latest/download/dev-nginx.tar.gz
          sudo cp mkcert-v1.4.3-linux-amd64 /usr/local/bin/mkcert
          sudo chmod +x /usr/local/bin/mkcert
          sudo mkdir -p /usr/local/bin/dev-nginx
          sudo tar -xzf dev-nginx.tar.gz -C /usr/local
          sudo chmod +x /usr/local/bin/dev-nginx
          sudo dev-nginx setup-cert "profile.thegulocal.com"
          sudo cp ./scripts/nginx.conf /etc/nginx/nginx.conf
          sudo dev-nginx restart-nginx
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: build
      - name: Unzip build
        run: unzip -q build.zip
      - uses: pnpm/action-setup@v6
      - name: Setup node
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: '.nvmrc'
      - name: Get pnpm cache directory path
        id: pnpm-cache-dir
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Cache pnpm modules and Playwright browsers
        uses: actions/cache@v5
        id: pnpm-cache
        with:
          path: |
            ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE_PATH }}
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-pnpm-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-playwright-
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: Start mock server
        run: pnpm run mock-server &
      - name: Start server
        run: pnpm start &
      - name: Wait for servers
        run: pnpm exec wait-on https://profile.thegulocal.com/healthcheck http://localhost:9000/healthcheck -t 60000
      - name: Run Playwright mocked tests
        run: pnpm exec playwright test --project=mocked --shard=${{ matrix.shard }}/${{ matrix.shardTotal }}
      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: playwright-report-mocked-${{ matrix.shard }}
          path: playwright-report/
          retention-days: 30
