export { default as SATURDAY_EDITION_SMALL_SQUARE_IMAGE } from '@/client/assets/newsletters/saturday-edition-small-square.jpg';
export { default as MORNING_MAIL_AU_SQUARE_IMAGE } from '@/client/assets/newsletters/au-morning-mail-square.png';
export { default as AFTERNOON_UPDATE_AU_SQUARE_IMAGE } from '@/client/assets/newsletters/au-afternoon-update-square.png';
export { default as SAVED_FOR_LATER_AU_SQUARE_IMAGE } from '@/client/assets/newsletters/au-saved-for-later-square.jpg';
export { default as THE_CRUNCH_AU_SQUARE_IMAGE } from '@/client/assets/newsletters/au-the-crunch-square.jpg';
export { default as HEADLINES_US_SQUARE_IMAGE } from '@/client/assets/newsletters/us-headlines-square.png';
export { default as THE_STAKES_US_SQUARE_IMAGE } from '@/client/assets/newsletters/us-the-stakes-square.jpg';
export { default as WELL_ACTUALLY_SQUARE_IMAGE } from '@/client/assets/newsletters/well-actually-square.jpg';
export { default as TRUMP_ON_TRIAL_US_SQUARE_IMAGE } from '@/client/assets/newsletters/us-trump-on-trial-square.jpg';
